### PR TITLE
Add missing semi-colon to `--layout-fullbleed`

### PR DESCRIPTION
**Pull request by blasten**
Fixes https://github.com/PolymerElements/iron-flex-layout/issues/56

### CODE REVIEW

**Comment by ebidel** [comment]
Bwah! https://github.com/PolymerElements/iron-flex-layout/pull/57

**Comment by blasten** [comment]
I know. I trust in your PR :)

**Comment by ebidel** [comment]
Derp. I thought you merged

**Comment by ebidel** [comment]
Ok, committed in https://github.com/PolymerElements/iron-flex-layout/commit/0c8d809bc2e3ba1fae9c15d022a0272f7f4578ca

**Comment by blasten** [comment]
let's just merge it! you want to merge mine?

**Pull request closed without merging**
