### PR TITLE
remove delinquent semicolon

### PR DESCRIPTION
**Pull request by notwaldorf**
Fixes https://github.com/PolymerElements/iron-flex-layout/issues/97

R: @valdrinkoshi

### CODE REVIEW

**Comment by valdrinkoshi** [comment]
Lol, LGTM :+1:

**Comment by valdrinkoshi** [comment]
Sad that we can't see tests passing on Firefox :(
@azakus any updates on this?

**Comment by web-padawan** [comment]
@notwaldorf this fix is still untagged which is a problem when using `clean-css` 4.0. 
Would you tag it as a patch release?

**Comment by notwaldorf** [comment]
Done! Sorry about that!

**Pull request merged**
