### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Jookus**
I think there is a small numbering mistake ;)

### CODE REVIEW

**Comment by Jookus** [comment]
I signed it!

**Comment by abdonrd** [comment]
The README is automatically generated from the comments in the [iron-flex-layout.html](https://github.com/PolymerElements/iron-flex-layout/blob/master/iron-flex-layout.html) file.

Edit this file, and the readme bot will duplicate them over here! :)

**Comment by Jookus** [comment]
Okay thank you, but in that file this "mistake" is already fixed?!

**Comment by abdonrd** [comment]
@Jookus right...

@azakus @rictic @justinfagnani maybe can help with it. I think that they works in [Tedium](https://github.com/PolymerLabs/tedium).

**Comment by azakus** [comment]
This looks like a bug in tedium, since it is numbered correctly here: https://github.com/PolymerElements/iron-flex-layout/blob/master/iron-flex-layout.html#L32

**Comment by rictic** [comment]
Tedium will change all numbers to `1.`, but that shouldn't affect the rendered form. The underlying issue is that the indentation isn't quite right. #84 should fix.

**Pull request closed without merging**
