### PR TITLE
Fix for IE breaking flex-basis

### PR DESCRIPTION
**Pull request by vsimonian**
IE has some very odd behavior with `flex`. Assigning `flex: [flex-grow];` causes IE to assign a default of `0px `to `flex-basis` instead of `auto`:

ie flex-basis inspector

This leads to some really, ***really*** undesirable results.

Using the `<paper-item>` demo as an example:

**IE, before fix:**

paper-item ie 11 broken

Manually specifying `flex-basis: auto` (or using the `flex` syntax, `flex: [flex-grow] auto`) fixes the problem by setting `flex-basis` to what it really should be by default.

**IE, after fix:**

paper-item ie 11 fixed

**Chrome, for reference:**

chrome paper-item ok

### CODE REVIEW

**Comment by morethanreal** [comment]
@frankiefu can you take a look at this?

**Comment by robrez** [comment]
I notice that, with regard to flex basis, there is a difference here...

`--layout-flex` in iron-flex-layout.html:
```
      -ms-flex: 1 1 0.000000001px;
      -webkit-flex: 1;
      flex: 1;
      -webkit-flex-basis: 0.000000001px;
      flex-basis: 0.000000001px;
```

`.flex` in classes/iron-flex-layout.html (before this patch):
```
    -ms-flex: 1;
    -webkit-flex: 1;
    flex: 1;
```

`html /deep/ .flex` in classes/iron-shadow-flex-layout.html (before this patch):
```
    -ms-flex: 1;
    -webkit-flex: 1;
    flex: 1;
```

I'm thinking all of the "flex" classes should match and that the 1st theme should _not_ apply 0.000000001px as the flex-basis? Applying this patch _and_ replacing . "0.000000001px" w/ "auto" fixes the issue that was reported over here: 
https://github.com/PolymerElements/paper-tabs/issues/29

**Comment by robrez** [comment]
This looked promising for fixing my IE problems; however, the changes caused some adverse effects on some of my layouts :(...

From the spec, http://www.w3.org/TR/css-flexbox-1/#propdef-flex,
>When omitted from the flex shorthand, its specified value is 0%

The diagram there shows how space distribution is differs w/ flex-basis auto vs 0%.

Example layout that was effected adversely w/ this patch:
```
<div class="layout horizontal">

  <div id="col1" class="layout vertical flex">
    <div>Some long content blah blah</div>
  </div>

  <div id="col2" class="layout vertical flex">
    <div>Hi</div>
  </div>

</div>
```

Prior to the patch, each column's width would match. After the patch, the 1st column was given a larger width because its content was larger.

Instead of applying this patch, I'm going through my code now and replacing several usages of `flex` with `flex-auto` wherever possible (iron-flex-layout already has a class that uses an auto basis) .

This IE flexbox discrepancy is a real bummer :-1: . I hope to find a nice solution that works universally.

**Comment by notwaldorf** [comment]
Closing this PR since it causes other breakages.

**Pull request closed without merging**
