### PR TITLE
apply `.layout` will be horizontal(row) by default.

### PR DESCRIPTION
**Pull request by Herobs**

### CODE REVIEW

**Comment by Herobs** [comment]
I signed it!

**Comment by Herobs** [comment]
Close #93

**Comment by z2oh** [comment]
Are CSS class changes considered breaking changes? Our deploy process pulled this latest release (we had `^1.0.0` tagged in our bower.json) and we spent a good while figuring out what caused our UI to break. All we needed to do was add the vertical class to all our divs that previously just had the layout class on them, but it took a while to narrow down exactly what was causing the issue.

**Comment by notwaldorf** [comment]
Oh hmmm they're definitely considered breaking changes. I didn't realize you could be using layout without "horizontal" or "vertical" -- sorry about that. Will send a fix today

**Pull request merged**
