### PR TITLE
Update documentation with closing </style> tag

### PR DESCRIPTION
**Pull request by mgiuffrida**

### CODE REVIEW

**Comment by notwaldorf** [comment]
LGTM but please squash your commits! :)

**Comment by mgiuffrida** [comment]
Ugh, I thought github would just do that. How's this?

**Comment by abdonrd** [comment]
LGTM, and I only see one commit. :)

**Comment by mgiuffrida** [comment]
Yeah, I didn't want to submit a new PR, so I did an interactive rebase
followed by a force push (apparently I'm Darth Vader) and GitHub helpfully
forgot the old patches ever existed. Is there a better way to change the
commits in the branch without losing past context in the PR?

**Comment by addyosmani** [comment]
This looks fine now. Thank you!

**Pull request closed without merging**
